version: '3.8'
services:
  postgres:
    container_name: "Ansyr-summer-practices"
    image: postgres:latest
    restart: on-failure
    environment:
      POSTGRES_DB : Bookmail
      POSTGRES_USER : postgres
      POSTGRES_PASSWORD : 1234
      POSTGRES_HOST : localhost
      POSTGRES_PORT : 54321
    ports:
      - "54321:5432"
    volumes:
      - ./dump:/var/lib/postgresql/data
